services:
  db:
    container_name: postgres
    image: postgres:14.6
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
  presa-api:
    container_name: presa-api
    image: zenwai/presa-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
  presa-frontend-react:
    container_name: presa-react
    image: zenwai/presa-react
    build:
      context: frontend/react
      args:
        api_base_url: http://localhost:8088
    ports:
      - "3000:5173"
    depends_on:
      - presa-api
    restart: unless-stopped
networks:
  db:
    driver: bridge

volumes:
  db: