server:
  port: 8080
  error:
    include-message: always

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

aws:
  region: eu-central-1
  s3:
    mock: false
    buckets:
      customer: fs-presa-customer

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
logging:
  level:
    org.springframework.jdbc: DEBUG
    org.springframework.jpa: DEBUG

Spring:
  datasource:
    url: jdbc:postgresql://awseb-e-vcti3p3w9c-stack-awsebrdsdatabase-oglhhgoa7pmn.c8jo8ln1gvnh.eu-central-1.rds.amazonaws.com:5432/ebdb
    username: amigoscode
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  codec:
    max-in-memory-size: 2MB